# Generated by Django 2.0.7 on 2018-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20180708_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isprivate',
            field=models.BooleanField(default=False, verbose_name='是否加密'),
        ),
        migrations.AddField(
            model_name='blog',
            name='password',
            field=models.TextField(blank=True, verbose_name='密码'),
        ),
    ]
